const data = [
  {
    id: "01",
    img: "../../assets/cello.jpg",
    alt: "cello",
    name: "Cello",
    info: "lorem iLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: 2100,
  },
  {
    id: "02",
    img: "../../assets/imgs/drum.jpg",
    alt: "drum",
    name: "Drum",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: 1500,
  },
  {
    id: "03",
    img: "../../assets/imgs/piano.jpg",
    alt: "piano",
    name: "Piano",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: 3500,
  },
  {
    id: "04",
    img: "../../assets/imgs/violin.jpg",
    alt: "violin",
    name: "Violin",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: 650,
  },
  {
    id: "05",
    img: "../../assets/imgs/saxophone.jpg",
    alt: "saxophone",
    name: "Saxophone",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: 820,
  },
  {
    id: "06",
    img: "../../assets/imgs/xylophone.jpg",
    alt: "xylophone",
    name: "Xylophone",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 820,
  },
  {
    id: "07",
    img: "../../assets/imgs/Guitar.jpg",
    alt: "Guitar",
    name: "Guitar",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 400,
  },
  {
    id: "08",
    img: "../../assets/imgs/Blue-Guitar.jpg",
    alt: "Blue Guitar",
    name: "Blue-Guitar",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 2400,
  },
  {
    id: "09",
    img: "../../assets/imgs/Microphone.jpg",
    alt: "Microphone",
    name: "Microphone",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 200,
  },
  {
    id: "10",
    img: "../../assets/imgs/Headphones.jpg",
    alt: "Headphones",
    name: "Headphones",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 400,
  },
  {
    id: "11",
    img: "../../assets/imgs/Harp.jpg",
    alt: "Harp",
    name: "Harp",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 1000,
  },
  {
    id: "12",
    img: "../../assets/imgs/Synthesizer.jpg",
    alt: "Synthesizer",
    name: "Synthesizer",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 5300,
  },
  {
    id: "13",
    img: "../../assets/imgs/Keyboard.jpg",
    alt: "Keyboard",
    name: "Keyboard",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 350,
  },
  {
    id: "14",
    img: "../../assets/imgs/Woodwind.jpg",
    alt: "Woodwind",
    name: "Woodwind",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 550,
  },
  {
    id: "15",
    img: "../../assets/imgs/Tambourine.jpg",
    alt: "Tambourine",
    name: "Tambourine",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 1000,
  },
  {
    id: "16",
    img: "../../assets/imgs/Stand.jpg",
    alt: "Stand",
    name: "Stand",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: 120,
  },
];

export default data;
